const baseListening = [
  {type:'短篇新闻',level:'基础 01',title:'Campus library extends its hours',text:'The university library will remain open until midnight during the final two weeks of the term. According to the library director, the change was made after many students asked for more quiet study space in the evening. Additional staff will be present, but the cafe will still close at nine o’clock.',question:'Why will the library stay open longer?',options:['To hold evening lectures.','To provide more study space.','To serve food until midnight.','To reduce the number of staff.'],answer:1},
  {type:'长对话',level:'基础 02',title:'Changing a meeting time',text:'Hi, Emma. Are we still meeting at the student center at three? I have a laboratory class that may finish late. Could we meet at half past three instead? That works for me. I will use the extra time to print our report. Great. I will bring the survey results, and we can finish the presentation together.',question:'What will the woman do before the meeting?',options:['Attend a laboratory class.','Collect survey results.','Print their report.','Finish the presentation alone.'],answer:2},
  {type:'听力篇章',level:'基础 03',title:'Why short breaks help',text:'When people study for a long time without stopping, their attention often becomes weaker. A brief break can help the brain recover. The break does not need to be long. Standing up, drinking water, or looking away from the screen for a few minutes may be enough. However, checking social media can easily turn a short pause into a much longer one.',question:'What does the speaker suggest doing during a short break?',options:['Checking social media.','Starting a new task.','Taking a short walk or drinking water.','Studying a different subject.'],answer:2},
  {type:'短篇新闻',level:'进阶 04',title:'A repair cafe opens downtown',text:'A community repair cafe opened downtown on Saturday. Volunteers helped visitors fix lamps, small appliances, and bicycles instead of throwing them away. The organizers say the monthly event is designed to reduce waste and allow neighbors to share practical skills. More than sixty objects were repaired on the first day.',question:'What is the main purpose of the repair cafe?',options:['To sell used appliances.','To train professional mechanics.','To reduce waste and share skills.','To collect money for volunteers.'],answer:2},
  {type:'长对话',level:'进阶 05',title:'Choosing a research topic',text:'I am having trouble choosing a topic for my history paper. I wanted to write about city parks, but the subject feels too broad. Why not focus on how one park changed the neighborhood around it? You could compare old maps with recent interviews. That sounds manageable. I know a local group that keeps an archive of photographs. Then you already have a good place to begin.',question:'What does the man advise the woman to do?',options:['Study one park in detail.','Choose a completely different subject.','Interview visitors before reading maps.','Write about every park in the city.'],answer:0}
];
let personalBank={};try{personalBank=JSON.parse(localStorage.getItem('cetPersonalBank')||'{}')||{}}catch{localStorage.removeItem('cetPersonalBank')}
const listeningMaterials=[...baseListening,...(window.CET_BANK?.listening||[]),...(Array.isArray(personalBank.listening)?personalBank.listening:[])];
const baseWords=[
  {w:'extend',p:'/ɪkˈstend/',m:'延长；扩大',e:'The library will extend its opening hours.'},
  {w:'additional',p:'/əˈdɪʃənl/',m:'额外的；附加的',e:'Additional staff will work in the evening.'},
  {w:'survey',p:'/ˈsɜːrveɪ/',m:'调查；问卷',e:'The survey results will be included in the report.'},
  {w:'attention',p:'/əˈtenʃn/',m:'注意力',e:'A short break can restore your attention.'},
  {w:'reduce',p:'/rɪˈduːs/',m:'减少',e:'The event aims to reduce waste.'},
  {w:'practical',p:'/ˈpræktɪkl/',m:'实用的；实际的',e:'Students shared practical skills.'},
  {w:'manageable',p:'/ˈmænɪdʒəbl/',m:'可处理的；可应付的',e:'A smaller topic is more manageable.'},
  {w:'archive',p:'/ˈɑːrkaɪv/',m:'档案；档案馆',e:'The group keeps an archive of old photographs.'}
];
const words=[...baseWords,...(window.CET_BANK?.words||[]),...(Array.isArray(personalBank.words)?personalBank.words:[])];

const defaultReasons={'词不认识':0,'认识但没听出':0,'句子没理解':0,'听懂但选错':0};
const defaultState={tasks:{},completed:0,reasons:{...defaultReasons},lastStudy:null,streak:0,word:0,readingDone:false};
let stored={};try{stored=JSON.parse(localStorage.getItem('cetLabState')||'{}')||{}}catch{localStorage.removeItem('cetLabState')}
let state={...defaultState,...stored,tasks:stored.tasks&&typeof stored.tasks==='object'?stored.tasks:{},reasons:{...defaultReasons,...(stored.reasons||{})}};
let currentListening=0,rate=.75,wordIndex=state.word||0,timer=null,seconds=480;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('cetLabState',JSON.stringify(state));renderProgress()}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
const dayNumber=Math.floor((new Date(localDate()+'T12:00:00')-new Date('2026-09-07T12:00:00'))/86400000);
currentListening=((dayNumber%listeningMaterials.length)+listeningMaterials.length)%listeningMaterials.length;
const dailyReading=(window.CET_BANK?.readings||[])[((dayNumber%Math.max(1,window.CET_BANK?.readings?.length||1))+Math.max(1,window.CET_BANK?.readings?.length||1))%Math.max(1,window.CET_BANK?.readings?.length||1)];
const dailyWriting=(window.CET_BANK?.writings||[])[Math.abs(dayNumber)%Math.max(1,window.CET_BANK?.writings?.length||1)];
const dailyTranslation=(window.CET_BANK?.translations||[])[Math.abs(dayNumber)%Math.max(1,window.CET_BANK?.translations?.length||1)];
function markStudy(){const today=localDate();const d=new Date();d.setDate(d.getDate()-1);const yesterday=localDate(d);if(state.lastStudy!==today){state.streak=state.lastStudy===yesterday?state.streak+1:1;state.lastStudy=today}}

function navigate(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(n=>{const active=n.dataset.view===id;n.classList.toggle('active',active);n.setAttribute('aria-current',active?'page':'false')});$('#mainNav').classList.remove('open');$('#menuButton').setAttribute('aria-expanded','false');$('#menuButton').setAttribute('aria-label','打开导航');window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>document.querySelector(`#${id} h1`)?.focus(),100)}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));
$('#homeButton').addEventListener('click',()=>navigate('today'));$('#menuButton').addEventListener('click',()=>{const open=$('#mainNav').classList.toggle('open');$('#menuButton').setAttribute('aria-expanded',open);$('#menuButton').setAttribute('aria-label',open?'关闭导航':'打开导航')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#mainNav').classList.remove('open');$('#menuButton').setAttribute('aria-expanded','false');$('#menuButton').setAttribute('aria-label','打开导航')}});

const beforeSoftExam=new Date()<new Date('2026-10-25T00:00:00');
$('#phaseText').textContent=beforeSoftExam?'软考前保持英语不断线':'四级冲刺期：增加限时训练';
$('#dateLine').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date()).toUpperCase();
$('#bankSummary').textContent=`题库已载入：${listeningMaterials.length} 道听力 · ${words.length} 个词汇 · ${window.CET_BANK?.readings?.length||0} 篇阅读`;
if(dailyReading){$('#readingPassageTitle').textContent=dailyReading.title;$('#readingPassage').innerHTML=dailyReading.text.map(p=>`<p>${p}</p>`).join('');$('#readingQuestionText').textContent=dailyReading.q;$('#readingOptions').innerHTML=dailyReading.options.map((o,i)=>`<label><input type="radio" name="reading" value="${i}"> ${o}</label>`).join('')}
$('#writingPrompt').textContent=`Write an essay on “${dailyWriting||'How to improve study habits'}”. State your view and support it with specific reasons or examples.`;
$('#translationPrompt').textContent=dailyTranslation||'良好的学习习惯有助于学生提高效率。';
const tasks=beforeSoftExam?[['精听一段','25 MIN','listening'],['复习声音词汇','10 MIN','vocab'],['记录错误原因','5 MIN','progress']]:[['精听与复盘','20 MIN','listening'],['限时阅读','10 MIN','reading'],['写译小练习','10 MIN','writing']];
function renderTasks(){const key=localDate();$('#taskList').innerHTML=tasks.map((t,i)=>`<label class="task"><input type="checkbox" data-task="${i}" ${state.tasks[key]?.includes(i)?'checked':''}><span><strong>${t[0]}</strong><small>${t[2]==='listening'?'今日重点':''}</small></span><span>${t[1]}</span></label>`).join('');const done=state.tasks[key]||[];$('#completedMinutes').textContent=tasks.reduce((s,t,i)=>s+(done.includes(i)?parseInt(t[1]):0),0);$$('[data-task]').forEach(c=>c.addEventListener('change',()=>{state.tasks[key]=state.tasks[key]||[];const i=+c.dataset.task;if(c.checked&&!state.tasks[key].includes(i)){state.tasks[key].push(i);state.completed++;markStudy()}else if(!c.checked){state.tasks[key]=state.tasks[key].filter(x=>x!==i);state.completed=Math.max(0,state.completed-1)}save();renderTasks()}))}renderTasks();

function renderWave(){const wave=$('#wave');wave.innerHTML=Array.from({length:72},(_,i)=>`<i style="height:${14+(i*17)%46}px"></i>`).join('')}
function speak(text,customRate=rate){if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){$('#audioStatus').textContent='此浏览器不支持语音播放，请换用最新版 Chrome、Edge 或 Safari。';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=customRate;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/en-US/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))||null;$('#audioStatus').textContent=u.voice?'':'正在使用设备默认英文语音；声音效果可能因设备而异。';u.onstart=()=>$('#wave').classList.add('playing');u.onend=()=>$('#wave').classList.remove('playing');u.onerror=()=>{$('#wave').classList.remove('playing');$('#audioStatus').textContent='语音播放失败。请检查设备是否安装了英文语音。'};speechSynthesis.speak(u)}
function renderListening(){const m=listeningMaterials[currentListening];$('#listeningList').innerHTML=listeningMaterials.map((x,i)=>`<button class="material-item ${i===currentListening?'active':''}" data-material="${i}" aria-current="${i===currentListening?'true':'false'}"><strong>${x.title}</strong><span>${x.type} · ${x.level}</span></button>`).join('');$('#listenType').textContent=m.type;$('#listenLevel').textContent=m.level;$('#listenTitleText').textContent=m.title;$('#transcriptText').textContent=m.text;$('#transcriptBox').open=false;$('#listenStep').textContent='第 1 步 / 盲听一次并作答';$('#listenQuestion').innerHTML=`<h3>${m.question}</h3>${m.options.map((o,i)=>`<label><input type="radio" name="listenAnswer" value="${i}"> ${String.fromCharCode(65+i)}. ${o}</label>`).join('')}<p class="feedback" id="listenFeedback" role="status" aria-live="polite"></p>`;const sentences=m.text.match(/[^.!?]+[.!?]+/g)||[m.text];$('#sentenceButtons').innerHTML=sentences.map((s,i)=>`<button class="sentence-button" data-sentence="${i}">句 ${i+1} ▶</button>`).join('');$$('[data-material]').forEach(b=>b.addEventListener('click',()=>{currentListening=+b.dataset.material;renderListening()}));$$('[name="listenAnswer"]').forEach(r=>r.addEventListener('change',()=>{const ok=+r.value===m.answer;$('#listenFeedback').textContent=ok?'答对了。现在打开原文，确认每个声音细节。':`再听一次。答案是 ${String.fromCharCode(65+m.answer)}，随后用原文定位没听懂的地方。`;$('#listenFeedback').className='feedback '+(ok?'correct':'wrong');$('#listenStep').textContent='第 2 步 / 重听并核对原文'}));$$('[data-sentence]').forEach(b=>b.addEventListener('click',()=>speak(sentences[+b.dataset.sentence],.72)))}
renderWave();renderListening();$('#playAudio').addEventListener('click',()=>speak(listeningMaterials[currentListening].text));$$('.speed-button').forEach(b=>b.addEventListener('click',()=>{rate=+b.dataset.rate;$$('.speed-button').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',active)});toast(`播放速度已设为 ${rate}×`)}));$$('[data-reason]').forEach(b=>b.addEventListener('click',()=>{$$('[data-reason]').forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-pressed','false')});b.classList.add('selected');b.setAttribute('aria-pressed','true')}));$('#finishListening').addEventListener('click',()=>{const answer=$('[name="listenAnswer"]:checked');if(!answer){toast('请先听材料并选择答案');return}const wrong=+answer.value!==listeningMaterials[currentListening].answer;const selected=$('[data-reason].selected');if(wrong&&!selected){toast('请记录这次没听懂的主要原因');return}if(selected){state.reasons[selected.dataset.reason]=(state.reasons[selected.dataset.reason]||0)+1;selected.classList.remove('selected')}state.completed++;markStudy();save();currentListening=(currentListening+1)%listeningMaterials.length;renderListening();toast('已记录。本段隔天再复听一次。')});

function renderWord(){const w=words[wordIndex%words.length];$('#wordIndex').textContent=`${wordIndex%words.length+1} / ${words.length}`;$('#wordText').textContent=w.w;$('#phonetic').textContent=w.p;$('#meaning').textContent=w.m;$('#example').textContent=w.e;$('#flashcard').classList.remove('flipped');$('#flipCard').setAttribute('aria-expanded','false');$('#cardBack').setAttribute('aria-hidden','true')}renderWord();
$('#flipCard').addEventListener('click',()=>{$('#flashcard').classList.add('flipped');$('#flipCard').setAttribute('aria-expanded','true');$('#cardBack').setAttribute('aria-hidden','false')});$('#speakWord').addEventListener('click',()=>speak(words[wordIndex%words.length].w,.7));$$('[data-recall]').forEach(b=>b.addEventListener('click',()=>{wordIndex++;state.word=wordIndex;state.completed++;markStudy();save();renderWord()}));

$('#checkReading').addEventListener('click',()=>{const a=$('[name="reading"]:checked');if(!a){toast('请先选择一个答案');return}const correct=dailyReading?.answer??1;const ok=+a.value===correct;$('#readingFeedback').textContent=ok?'正确。请回到原文确认支撑答案的句子。':`答案是 ${String.fromCharCode(65+correct)}。请回到原文定位依据，并说明其他选项为什么不成立。`;$('#readingFeedback').className='feedback '+(ok?'correct':'wrong');const key=`reading-${localDate()}`;if(!state[key]){state.completed++;state[key]=true;markStudy();save()}});
$('#readingTimer').addEventListener('click',()=>{if(timer){clearInterval(timer);timer=null;$('#readingTimer').textContent='继续计时';return}timer=setInterval(()=>{seconds--;const m=Math.floor(seconds/60),s=seconds%60;$('#readingTimer').textContent=`${m}:${String(s).padStart(2,'0')}`;if(seconds<=0){clearInterval(timer);timer=null;toast('8分钟到，请提交答案')}} ,1000)});
const editor=$('#writingEditor');editor.value=localStorage.getItem('cetWriting')||'';function countWords(){const n=(editor.value.trim().match(/[A-Za-z]+(?:'[A-Za-z]+)?/g)||[]).length;$('#wordCount').textContent=`${n} words`}editor.addEventListener('input',()=>{localStorage.setItem('cetWriting',editor.value);countWords()});countWords();$('#clearWriting').addEventListener('click',()=>{if(confirm('确认清空当前作文？')){editor.value='';localStorage.removeItem('cetWriting');countWords()}});

function renderProgress(){$('#streakCount').innerHTML=`${state.streak||0}<small> 天</small>`;$('#sessionCount').innerHTML=`${state.completed||0}<small> 项</small>`;const max=Math.max(1,...Object.values(state.reasons));$('#diagnosticChart').innerHTML='<h2>听力卡点</h2>'+Object.entries(state.reasons).map(([k,v])=>`<div class="chart-row"><span>${k}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join('')}renderProgress();
$('#exportData').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cet-lab-progress.json';a.click();URL.revokeObjectURL(a.href)});$('#resetData').addEventListener('click',()=>{if(confirm('确认重置所有本机学习记录？此操作无法撤销。')){state={...defaultState,reasons:{...defaultState.reasons},tasks:{}};localStorage.removeItem('cetLabState');renderTasks();renderProgress();toast('学习记录已重置')}});

$('#importBank').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;const status=$('#importStatus');try{const data=JSON.parse(await file.text());const incoming={listening:Array.isArray(data.listening)?data.listening:[],words:Array.isArray(data.words)?data.words:[]};const validListening=incoming.listening.every(x=>x&&typeof x.title==='string'&&typeof x.text==='string'&&typeof x.question==='string'&&Array.isArray(x.options)&&x.options.length===4&&Number.isInteger(x.answer)&&x.answer>=0&&x.answer<4);const validWords=incoming.words.every(x=>x&&typeof x.w==='string'&&typeof x.m==='string');if(!validListening||!validWords||(!incoming.listening.length&&!incoming.words.length))throw new Error('题包结构不正确');const merged={listening:[...(personalBank.listening||[]),...incoming.listening],words:[...(personalBank.words||[]),...incoming.words]};localStorage.setItem('cetPersonalBank',JSON.stringify(merged));status.textContent=`导入成功：${incoming.listening.length} 道听力、${incoming.words.length} 个词汇。页面即将刷新。`;setTimeout(()=>location.reload(),900)}catch(error){status.textContent=`导入失败：${error.message}。请确认文件是平台支持的 JSON 题包。`}finally{event.target.value=''}});

if('serviceWorker' in navigator&&location.protocol.startsWith('http')){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}



